{
 "title": "Visual search",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of search requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum_over_time(\n  sum by (status) (\n    delta(http_requests_total{handler=\"/collections/{collection_id}/search\", method=\"POST\"}[$__interval])\n  )[$__interval:]\n)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/collections/{collection_id}/search\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/collections/{collection_id}/search\"}[5m])) / 1024",
       "legendFormat": "Average Size (kB)"
      }
     ]
    },
    {
     "title": "Average latency of search request (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/collections/{collection_id}/search\", method=\"POST\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{handler=\"/collections/{collection_id}/search\", method=\"POST\"}[5m]))\n",
       "legendFormat": "Average latency (s)"
      }
     ]
    },
    {
     "title": "Average output response size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(http_response_size_bytes_sum{handler=\"/collections/{collection_id}/search\"}[5m]))\n/\nsum(rate(http_response_size_bytes_count{handler=\"/collections/{collection_id}/search\"}[5m])) / 1024\n",
       "legendFormat": "Average Size (kB}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ingest requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum_over_time(\n  sum by (status) (\n    delta(http_requests_total{handler=\"/collections/{collection_id}/documents\", method=\"POST\"}[$__interval])\n  )[$__interval:]\n)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/collections/{collection_id}/documents\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/collections/{collection_id}/documents\"}[5m])) / 1024",
       "legendFormat": "Average Size (kB)"
      }
     ]
    },
    {
     "title": "Average latency of ingest request (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/collections/{collection_id}/documents\", method=\"POST\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{handler=\"/collections/{collection_id}/documents\", method=\"POST\"}[5m]))\n",
       "legendFormat": "Average latency (s)"
      }
     ]
    },
    {
     "title": "Average output response size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(http_response_size_bytes_sum{handler=\"/collections/{collection_id}/documents\"}[5m]))\n/\nsum(rate(http_response_size_bytes_count{handler=\"/collections/{collection_id}/documents\"}[5m])) / 1024\n",
       "legendFormat": "Average Size (kB}"
      }
     ]
    }
   ]
  },
  {
   "title": "Embeddings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ingest requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum_over_time(\n  sum by (status) (\n    delta(http_requests_total{handler=\"/collections/{collection_id}/embeddings\", method=\"POST\"}[$__interval])\n  )[$__interval:]\n)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/collections/{collection_id}/embeddings\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/collections/{collection_id}/embeddings\"}[5m])) / 1024",
       "legendFormat": "Average Input Size (kB)"
      }
     ]
    },
    {
     "title": "Average latency of ingest request (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/collections/{collection_id}/embeddings\", method=\"POST\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{handler=\"/collections/{collection_id}/embeddings\", method=\"POST\"}[5m]))\n",
       "legendFormat": "Average latency (s)"
      }
     ]
    },
    {
     "title": "Average output response size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(http_response_size_bytes_sum{handler=\"/collections/{collection_id}/embeddings\"}[5m])) / sum(rate(http_response_size_bytes_count{handler=\"/collections/{collection_id}/embeddings\"}[5m])) / 1024",
       "legendFormat": "Average Response Size (kB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of collection requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum_over_time(\n  sum by (status) (\n    delta(http_requests_total{handler=\"/collections\"}[$__interval])\n  )[$__interval:]\n)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/collections\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/collections\"}[5m])) / 1024",
       "legendFormat": "Average Input Size (kB)"
      }
     ]
    },
    {
     "title": "Average latency of linear probe request (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/collections\", method=\"GET\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{handler=\"/collections\", method=\"GET\"}[5m]))\n",
       "legendFormat": "Average latency (s)"
      }
     ]
    },
    {
     "title": "Average output response size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(http_response_size_bytes_sum{handler=\"/collections\", job=\"visual-search\"}[5m])) / sum(rate(http_response_size_bytes_count{handler=\"/collections\", job=\"visual-search\"}[5m])) / 1024",
       "legendFormat": "Average Response Size (kB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Linear probe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of linear probe requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum_over_time(\n  sum by (status) (\n    delta(http_requests_total{handler=\"/linear_probe\", method=\"POST\"}[$__interval])\n  )[$__interval:]\n)",
       "legendFormat": "Status: {{status}}"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/linear_probe\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/linear_probe\"}[5m])) / 1024",
       "legendFormat": "Average Input Size (kB)"
      }
     ]
    },
    {
     "title": "Average latency of linear probe request (s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{handler=\"/linear_probe\", method=\"POST\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{handler=\"/linear_probe\", method=\"POST\"}[5m]))\n",
       "legendFormat": "Average latency (s)"
      }
     ]
    },
    {
     "title": "Average output response size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(http_response_size_bytes_sum{handler=\"/linear_probe\"}[5m])) / sum(rate(http_response_size_bytes_count{handler=\"/linear_probe\"}[5m])) / 1024",
       "legendFormat": "Average Response Size (kB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of storage requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by(status) (\n  rate(http_requests_total{job=\"visual-search-storage\", method=\"POST\", handler=\"/write\"}[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average input request size (kB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(http_request_size_bytes_sum{handler=\"/write\", job=\"visual-search-storage\"}[5m])) / sum(rate(http_request_size_bytes_count{handler=\"/write\", job=\"visual-search-storage\"}[5m])) / 1024",
       "legendFormat": "Average Size (kB)"
      }
     ]
    }
   ]
  },
  {
   "title": "Inference",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilisation (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "nv_gpu_utilization{job=~\"^triton-.*\"} * 100.0",
       "legendFormat": "{{container}}-{{gpu_uuid}}"
      }
     ]
    },
    {
     "title": "GPU Memory Usage (GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "nv_gpu_memory_used_bytes{job=~\"^triton-.*\"} / (1024 * 1024 * 1024)",
       "legendFormat": "{{container}}-{{gpu_uuid}}"
      }
     ]
    },
    {
     "title": "CPU Utilisation (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "nv_cpu_utilization{job=~\"^triton-.*\"} * 100.0",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "CPU Memory Usage (GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "nv_cpu_memory_used_bytes{job=~\"^triton-.*\"} / (1024 * 1024 * 1024)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}