# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nim-cluster
  region: us-east-2
  version: "1.28"

iam:
  withOIDC: true

addons:
- name: aws-ebs-csi-driver

nodeGroups:
  - name: system-nodes
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    amiFamily: AmazonLinux2023

  - name: gpu-nodes
    instanceType: g6.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    amiFamily: AmazonLinux2023
    labels:
      nvidia.com/gpu.present: "true"